### ISSUE TITLE
Having 'time' as the first of multiple requests will cause an error

### ISSUE THREAD

**Issue by rdecorsi** [TWOEARS/auditory-front-end#1] opened 2015-02-05 13:15 UTC
Requesting time domain representations (output of the pre-processor) as first in a multiple request scenario will generate an error, for example:

```
>> mObj.addProcessor({'time','ild'});
Index exceeds matrix dimensions.

Error in manager/addProcessor (line 592)
                    dep_sig_l = mObj.Processors{2,1}.Input;

Error in manager/addProcessor (line 495)
                    varargout{ii-1} = mObj.addProcessor(request{ii},p{ii});
```

A temporary fix is to re-order the requests to avoid time being the first one, e.g., `mObj.addProcessor({'ild','time'});`. 
Note that an explicit `'time'` request is usually unnecessary, as the pre-processing step is always applied for all other requests and the `'time'` signal can be accessed through `'mObj.Data.time'`, unless, of course, this representation is requested with a set of different parameters of its own.

**Comment by hagenw** [comment] 2016-09-27 20:46
@Hardcorehobel: could you please test if this bug still exists. If yes and there is no easy way to fix it, we should include a warning in the documentation that you cannot add time as a first value.

**Comment by Hardcorehobel** [comment] 2016-09-29 07:49
I cannot reproduce this bug. Using time as a first request in a multiple-request scenario works for me.

**Comment by hagenw** [comment] 2016-09-29 07:54
I was not able to test this as I have no Matlab on my Laptop, I just saw that this bug was still open. So I would assume that the problem no longer exists. If you like I can test it next week, or you can close it directly.

**Comment by Hardcorehobel** [comment] 2016-12-13 16:32
This doesn't seem to be a problem anymore.

**Closed as completed by Hardcorehobel** 2016-12-13 16:32 UTC
Labels: bug
